version: '3.8'

services:
  api:
    build:
      context: ./packages/api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./packages/api:/app
    environment:
      - NODE_ENV=development

  ui:
    build:
      context: ./packages/ui
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./packages/ui:/app
    environment:
      - NODE_ENV=development
